// ios/Headstart/Theme/Typography.swift
import SwiftUI
import UIKit

/// Archivo 400/500/600/700, bundled as static faces generated by
/// `ios/scripts/make-fonts.sh`. Falls back to the system font if the files are
/// missing so the app never crashes on a bad build — the unit test, not a
/// runtime crash, is what tells you the fonts are gone.
public enum HSFont {
    public static let familyName = "Archivo"

    public static var isArchivoAvailable: Bool {
        !UIFont.fontNames(forFamilyName: familyName).isEmpty
    }

    /// PostScript names of the four bundled faces, nearest-weight for anything else.
    public static func faceName(for weight: Font.Weight) -> String {
        switch weight {
        case .bold, .heavy, .black:
            return "Archivo-Bold"
        case .semibold:
            return "Archivo-SemiBold"
        case .medium:
            return "Archivo-Medium"
        default:
            return "Archivo-Regular"
        }
    }

    public static func font(_ size: CGFloat, _ weight: Font.Weight) -> Font {
        guard isArchivoAvailable else { return .system(size: size, weight: weight) }
        return .custom(faceName(for: weight), fixedSize: size)
    }
}

public extension Font {
    /// Body and heading text. `fixedSize` on purpose: the artboards are pixel-specified
    /// at 390 pt and Dynamic Type scaling would break the 56 pt control grid. Accessibility
    /// text sizes are an M4 item tracked against the store listing.
    static func hs(_ size: CGFloat, _ weight: Font.Weight = .regular) -> Font {
        HSFont.font(size, weight)
    }

    /// Every countdown, ETA and clock time. Tabular figures so digits don't jitter
    /// while the number ticks (CLIENT_CONTRACT.md §Design tokens).
    static func hsNum(_ size: CGFloat, _ weight: Font.Weight = .bold) -> Font {
        HSFont.font(size, weight).monospacedDigit()
    }
}

public extension View {
    /// The uppercase, wide-tracked eyebrow used on every section label in the artboards.
    func hsEyebrowTracking() -> some View { tracking(1.4) }
}
